<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>0bd8eb2e-565e-4baf-8b5b-f87c8c64f5cf</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.4.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\App\MiPlataforma.App.Api\MiPlataforma.App.Api.csproj" />
    <ProjectReference Include="..\App\MiPlataforma.App.Bff\MiPlataforma.App.Bff.csproj" />
  </ItemGroup>

</Project>
